// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (merchant_id, name, key_prefix, key_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, merchant_id, name, key_prefix, key_hash, revoked_at, created_at
`

type CreateAPIKeyParams struct {
	MerchantID pgtype.UUID
	Name       string
	KeyPrefix  string
	KeyHash    string
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (*ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.MerchantID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, merchant_id, revoked_at
FROM api_keys
WHERE key_hash = $1
`

type GetAPIKeyByHashRow struct {
	ID         pgtype.UUID
	MerchantID pgtype.UUID
	RevokedAt  pgtype.Timestamptz
}

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (*GetAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i GetAPIKeyByHashRow
	err := row.Scan(&i.ID, &i.MerchantID, &i.RevokedAt)
	return &i, err
}

const listAPIKeysByMerchantID = `-- name: ListAPIKeysByMerchantID :many
SELECT id, merchant_id, name, key_prefix, key_hash, revoked_at, created_at FROM api_keys
WHERE merchant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByMerchantID(ctx context.Context, merchantID pgtype.UUID) ([]*ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByMerchantID, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Name,
			&i.KeyPrefix,
			&i.KeyHash,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys
SET revoked_at = now()
WHERE id = $1 AND merchant_id = $2 AND revoked_at IS NULL
`

type RevokeAPIKeyParams struct {
	ID         pgtype.UUID
	MerchantID pgtype.UUID
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.MerchantID)
	return err
}
