// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (merchant_id, customer_id, sku_id, amount, sent_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertEventParams struct {
	MerchantID pgtype.UUID
	CustomerID pgtype.UUID
	SkuID      pgtype.UUID
	Amount     float64
	SentAt     pgtype.Timestamptz
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.MerchantID,
		arg.CustomerID,
		arg.SkuID,
		arg.Amount,
		arg.SentAt,
	)
	return err
}

const listEvents = `-- name: ListEvents :many
SELECT id, merchant_id, customer_id, sku_id, amount, sent_at FROM events
`

func (q *Queries) ListEvents(ctx context.Context) ([]*Event, error) {
	rows, err := q.db.Query(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.CustomerID,
			&i.SkuID,
			&i.Amount,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
