// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: merchants.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMerchant = `-- name: CreateMerchant :one
INSERT INTO merchants (email, password_hash, name)
VALUES ($1, $2, $3)
RETURNING id, email, name, created_at, updated_at
`

type CreateMerchantParams struct {
	Email        string
	PasswordHash string
	Name         string
}

type CreateMerchantRow struct {
	ID        pgtype.UUID
	Email     string
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateMerchant(ctx context.Context, arg CreateMerchantParams) (*CreateMerchantRow, error) {
	row := q.db.QueryRow(ctx, createMerchant, arg.Email, arg.PasswordHash, arg.Name)
	var i CreateMerchantRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getMerchantByEmail = `-- name: GetMerchantByEmail :one
SELECT id, email, password_hash, name, created_at, updated_at
FROM merchants
WHERE email = $1
`

func (q *Queries) GetMerchantByEmail(ctx context.Context, email string) (*Merchant, error) {
	row := q.db.QueryRow(ctx, getMerchantByEmail, email)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getMerchantByID = `-- name: GetMerchantByID :one
SELECT id, email, name, created_at, updated_at
FROM merchants
WHERE id = $1
`

type GetMerchantByIDRow struct {
	ID        pgtype.UUID
	Email     string
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetMerchantByID(ctx context.Context, id pgtype.UUID) (*GetMerchantByIDRow, error) {
	row := q.db.QueryRow(ctx, getMerchantByID, id)
	var i GetMerchantByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
