// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID         pgtype.UUID
	MerchantID pgtype.UUID
	CustomerID pgtype.UUID
	SkuID      pgtype.UUID
	Amount     float64
	SentAt     pgtype.Timestamptz
}

type Merchant struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	Name         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type SchemaMigration struct {
	Version string
}
