// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: skus.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSKU = `-- name: CreateSKU :one
INSERT INTO skus (merchant_id, name, unit, price_per_unit)
VALUES ($1, $2, $4, $3)
RETURNING id, merchant_id, name, unit, price_per_unit, revoked_at, created_at
`

type CreateSKUParams struct {
	MerchantID   pgtype.UUID
	Name         string
	PricePerUnit float64
	Unit         pgtype.Text
}

func (q *Queries) CreateSKU(ctx context.Context, arg CreateSKUParams) (*Sku, error) {
	row := q.db.QueryRow(ctx, createSKU,
		arg.MerchantID,
		arg.Name,
		arg.PricePerUnit,
		arg.Unit,
	)
	var i Sku
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Unit,
		&i.PricePerUnit,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const listSKUsByMerchantID = `-- name: ListSKUsByMerchantID :many
SELECT id, name, unit, price_per_unit, revoked_at, created_at
FROM skus
WHERE merchant_id = $1
ORDER BY created_at DESC
`

type ListSKUsByMerchantIDRow struct {
	ID           pgtype.UUID
	Name         string
	Unit         pgtype.Text
	PricePerUnit float64
	RevokedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) ListSKUsByMerchantID(ctx context.Context, merchantID pgtype.UUID) ([]*ListSKUsByMerchantIDRow, error) {
	rows, err := q.db.Query(ctx, listSKUsByMerchantID, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListSKUsByMerchantIDRow
	for rows.Next() {
		var i ListSKUsByMerchantIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Unit,
			&i.PricePerUnit,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSKU = `-- name: RevokeSKU :exec
UPDATE skus
SET revoked_at = now()
WHERE id = $1 AND merchant_id = $2 AND revoked_at IS NULL
`

type RevokeSKUParams struct {
	ID         pgtype.UUID
	MerchantID pgtype.UUID
}

func (q *Queries) RevokeSKU(ctx context.Context, arg RevokeSKUParams) error {
	_, err := q.db.Exec(ctx, revokeSKU, arg.ID, arg.MerchantID)
	return err
}
